[tool.ruff]
target-version = "py311"
exclude = ["versions", "venv", ".venv"]

lint.select = ["E", "F", "W", "C90", "I", "N", "B"]
lint.fixable = ["ALL"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"
